[styleTitle]
StringAlign=CENTER
StringCase=UPPER
StringStyle=BOLD
InlineSetting=Shadow | 1 | 1 | 1 | 0,0,0,100
FontColor=#colorText#
FontFace=#fontName1#
FontSize=9
AntiAlias=1
ClipString=1
AccurateText=1

[styleCurrentTemp]
StringAlign=LEFT
StringCase=NONE
StringStyle=BOLD
InlineSetting=Shadow | 1 | 1 | 1 | 0,0,0,100
FontColor=#colorText#
FontFace=#fontName1#
FontSize=18
AntiAlias=1
ClipString=1
AccurateText=1

[styleCurrentTempLarge]
StringAlign=LEFT
StringCase=NONE
StringStyle=BOLD
InlineSetting=Shadow | 1 | 1 | 1 | 0,0,0,100
FontColor=#colorText#
FontFace=#fontName2#
FontSize=18
AntiAlias=1
ClipString=1
AccurateText=1

[styleLeftText]
StringAlign=LEFT
StringCase=NONE
InlineSetting=Shadow | 1 | 1 | 1 | 0,0,0,100
FontColor=#colorText#
FontFace=#fontName1#
FontSize=#textSize#
AntiAlias=1
ClipString=1
AccurateText=1

[styleRightText]
StringAlign=RIGHT
StringCase=NONE
InlineSetting=Shadow | 1 | 1 | 1 | 0,0,0,100
FontColor=#colorText#
FontFace=#fontName1#
FontSize=#textSize#
AntiAlias=1
ClipString=1
AccurateText=1

[styleCenterText]
StringAlign=CENTER
StringCase=NONE
InlineSetting=Shadow | 1 | 1 | 1 | 0,0,0,100
FontColor=#colorText#
FontFace=#fontName1#
FontSize=#textSize#
AntiAlias=1
ClipString=0

[styleCenterRubik]
StringAlign=CENTER
StringCase=NONE
InlineSetting=Shadow | 1 | 1 | 1 | 0,0,0,100
FontColor=#colorText#
FontFace=#fontName1#
FontSize=#textSize#
AntiAlias=1
ClipString=0
AccurateText=1

[styleCenterRain]
StringAlign=CENTER
StringCase=NONE
FontFace=Rubik
FontColor=#colorText#
FontSize=#textSize#
InlineSetting=Shadow | 1 | 1 | 1 | 0,0,0,100
InlineSetting2=Face | Font Awesome 6 Free Solid
InlinePattern2=[\xf740]
AntiAlias=1
ClipString=0
AccurateText=1

[styleBar]
BarOrientation=HORIZONTAL
SolidColor=0,255,255,15